packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': false
  '@tensorflow/tfjs-node': false
  '@tensorflow/tfjs-node-gpu': false
  better-sqlite3: false
  core-js: false
  es5-ext: false
  esbuild: true
  sharp: false
  tesseract.js: false
  unrs-resolver: false
  workerd: false
