/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export interface ManaPool {
  W: number
  U: number
  B: number
  R: number
  G: number
  C: number
  S: number
  generic: number
}
export interface Card {
  id: string
  oracleId: string
  name: string
  manaCost: string
  cmc: number
  typeLine: string
  oracleText: string
  power?: string
  toughness?: string
  loyalty?: string
  colors: Array<string>
  colorIdentity: Array<string>
  tags: Array<string>
  imageUrl: string
  owner: number
}
export interface Permanent {
  id: string
  cardId: string
  controller: number
  owner: number
  name: string
  typeLine: string
  oracleText: string
  tapped: boolean
  flipped: boolean
  faceDown: boolean
  summoningSick: boolean
  damageMarked: number
  currentPower?: number
  currentToughness?: number
  cmc: number
}
export interface PlayerState {
  id: number
  name: string
  life: number
  poisonCounters: number
  manaPool: ManaPool
  hand: Array<Card>
  library: Array<Card>
  graveyard: Array<Card>
  exile: Array<Card>
  battlefield: Array<Permanent>
  commandZone: Array<Card>
  commanderTax: number
  commanderDamage?: Record<string, number>
  landPlayedThisTurn: boolean
  landsPlayedThisTurn: number
  maxLandPlays: number
  hasDrawnThisGame: boolean
}
export interface StackObject {
  id: string
  type: string
  card?: Card
  source?: Permanent
  controller: number
  text: string
}
export interface Target {
  type: string
  id: string
  zone?: string
}
export interface GameAction {
  type: string
  player: number
  cardId?: string
  sourceId?: string
  abilityIndex?: number
  targets?: Array<Target>
  toBottom?: Array<string>
}
export interface Attacker {
  permanentId: string
  targetId: string
}
export interface Blocker {
  permanentId: string
  attackerId: string
}
export interface CombatState {
  attackers: Array<Attacker>
  blockers: Array<Blocker>
  step: string
}
export interface GameState {
  players: Array<PlayerState>
  activePlayer: number
  priorityPlayer: number
  turn: number
  phase: string
  step: string
  stack: Array<StackObject>
  bothPlayersPassed: boolean
  gameOver: boolean
  winner?: number
  mulliganPhase: boolean
  mulliganCount: Array<number>
  log?: Array<GameLogEntry>
  actionHistory?: Array<GameAction>
  combat?: CombatState
}
export interface GameLogEntry {
  timestamp: number
  turn: number
  phase: string
  step: string
  player?: number
  message: string
  cardName?: string
  actionType?: string
}
export declare function createEmptyState(): GameState
export declare function helloWorld(): string
export declare function nativeValidateAction(state: GameState, action: GameAction): boolean
export declare function nativeApplyAction(state: GameState, action: GameAction): GameState
export declare function benchmarkSimulation(state: GameState, iterations: number): number
export declare class GameSession {
  constructor()
  applyAction(action: GameAction): void
  getTurn(): number
  isGameOver(): boolean
  getPriorityPlayer(): number
  getActivePlayer(): number
  getFeatures(player: number): Array<number>
  getLegalActions(player: number): Array<GameAction>
  getScore(player: number): number
}
